apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: userms
      context: .
      sync:
        manual:
          # sync a single file into the `/etc` folder
          - src: '**/*'
            dest: /var/virtualbank
#deploy:
#  kubectl:
#    manifests:
#      - ../kubernettes/authms/config-maps/*
#      - ../kubernettes/authms/secrets/*
#      - ../kubernettes/authms/dbserver/*
#      - ../kubernettes/authms/deployment.yaml
#      - ../kubernettes/authms/service.yaml

deploy:
  statusCheckDeadlineSeconds: 60
  helm:
    releases:
      - name: userms
        chartPath: ../kubernettes/ocb
        valuesFiles:
          - ../kubernettes/ocb/values.userms.yaml
        artifactOverrides:
          image: userms
        imageStrategy:
          helm: { }